#
# Copyright (C) 2021-2022 Intel Corporation
#
# SPDX-License-Identifier: MIT
#
version: '3.3'

services:
  cvat_server:
    build:
      context: .
      args:
        http_proxy:
        https_proxy:
        socks_proxy:
        CLAM_AV:
        INSTALL_SOURCES:
        COGNITO_USER_POOL_APP: ${COGNITO_USER_POOL_APP}
        COGNITO_CLIENT_ID: ${COGNITO_CLIENT_ID}
        COGNITO_REDIRECT_URI: ${COGNITO_REDIRECT_URI}

  cvat_ui:
    build:
      context: .
      args:
        http_proxy:
        https_proxy:
        no_proxy:
        socks_proxy:
      dockerfile: Dockerfile.ui
